Hw12 13 14 15 calendar
FreakyGranny/otus pull request #15
Opened 2020-09-26 07:06 UTC by FreakyGranny

## Домашнее задание №15 «Докеризация и интеграционное тестирование Календаря»

### Критерии оценки
- [ ] Проект полностью запускается и останавливается с помощью `make up` / `make down` - 3 балла
- [ ] Интеграционные тесты запускаются с помощью `make bdd`. Команда возвращает верный код ответа - 1 балл

Интеграционные тесты покрывают бизнес сценарии:
- [ ] добавление события и обработка бизнес ошибок - 2 балла
- [ ] получение листинга событий на день/неделю/месяц - 2 балла
- [ ] отправка уведомлений - 2 балла

#### Зачёт от 7 баллов

```
=== RUN   TestIntegration
=== RUN   TestIntegration/TestCreateInvalidDates
=== RUN   TestIntegration/TestCreateInvalidTitle
=== RUN   TestIntegration/TestList
=== RUN   TestIntegration/TestListEmpty
=== RUN   TestIntegration/TestListInvalidMonthDay
=== RUN   TestIntegration/TestListInvalidWeekday
=== RUN   TestIntegration/TestUpdate
=== RUN   TestIntegration/TestValidCreate
--- PASS: TestIntegration (0.12s)
    --- PASS: TestIntegration/TestCreateInvalidDates (0.00s)
    --- PASS: TestIntegration/TestCreateInvalidTitle (0.00s)
    --- PASS: TestIntegration/TestList (0.06s)
    --- PASS: TestIntegration/TestListEmpty (0.00s)
    --- PASS: TestIntegration/TestListInvalidMonthDay (0.00s)
    --- PASS: TestIntegration/TestListInvalidWeekday (0.01s)
    --- PASS: TestIntegration/TestUpdate (0.03s)
    --- PASS: TestIntegration/TestValidCreate (0.01s)
PASS
ok  	github.com/FreakyGranny/otus/hw12_13_14_15_calendar/tests/integration	0.127s
```

2020-09-26 10:00 UTC, kulti requested changes
Не могу проверить работу с интеграционными тестами из-за некорректного докерфайла.

Все остальное выгляди хорошо. Жду фикса для докерфайла, чтобы подробнее потыкать интеграционные тесты.

2020-09-26 10:00 UTC, kulti commented on hw12_13_14_15_calendar/deployments/docker-compose.yaml
> +    command: sh -c "/wait && /app/calendar migrate up --config config.yaml"
Это некорректное ожидание БД.

wait ждет только открытый tcp-порт. Postgres же становится рабочим несколько позже.

Правильно будет выполнять простой запрос к БД или еще как-то с ней взаимодействовать. Например, можно делать `SELECT 1`. Рекомендую прочитать — https://docs.docker.com/compose/startup-order/

2020-09-26 10:00 UTC, kulti commented on hw12_13_14_15_calendar/deployments/docker-compose.yaml
> +  sender:
Рекомендую отделять сервисы пустой строкой. Так файл будет лучше читаться.

2020-09-26 10:00 UTC, kulti commented on hw12_13_14_15_calendar/Dockerfile
> +COPY bin/calendar /app
Копировать бинарник внутрь докер-образа так себе затея.

Docker на винде и маке работает в виртуалке с линуксом. Здесь же скопируется бинарних хостовой системы, который не запуститься. Из-за этого я не могу проверить работу make integration-test.

Для лучшей повторяемости сборки стоит собирать бинарник внутри докерфайла. Хорошая статья на тему — https://medium.com/@chemidy/create-the-smallest-and-secured-golang-docker-image-based-on-scratch-4752223b7324. Все оттуда можно сейчас не брать, в первую очередь обратите внимание на мульти-стейдж билд.

2020-09-26 10:00 UTC, kulti commented on hw12_13_14_15_calendar/tests/integration/integration_test.go
> +	s.Init(apiURL)
Здесь, наверно, нет смысла выделять Init в метод. В моем проекте task-list сделано, чтобы сьют два раза использовать и инициализировать его для работы с разными серверами.

Можно код Init встроить в SetupTest, который, по сути, и является инициализацией теста.

Также рекомендую располагать методы сверху вниз, чтобы можно было читать код последовательно, как книгу, и не прыгать по нему туда-сюда.

2020-09-26 10:00 UTC, kulti commented on hw12_13_14_15_calendar/tests/integration/integration_test.go
> +	s.Require().Nil(err)
Рекомендую использовать хелпер NoError. С ним код и ошибка станут чище и понятнее.

2020-09-26 15:53 UTC, FreakyGranny commented on hw12_13_14_15_calendar/Dockerfile
> +COPY bin/calendar /app
Понял, просто привык на работе что у всех линукс и в CI линукс.

2020-09-26 15:53 UTC, FreakyGranny commented on hw12_13_14_15_calendar/deployments/docker-compose.yaml
> +  sender:
поправил

2020-09-26 15:54 UTC, FreakyGranny commented on hw12_13_14_15_calendar/tests/integration/integration_test.go
> +	s.Init(apiURL)
поправил, надеюсь я правильно вас понял)

2020-09-26 15:54 UTC, FreakyGranny commented on hw12_13_14_15_calendar/tests/integration/integration_test.go
> +	s.Require().Nil(err)
поправил

2020-09-26 16:01 UTC, FreakyGranny commented on hw12_13_14_15_calendar/deployments/docker-compose.yaml
> +    command: sh -c "/wait && /app/calendar migrate up --config config.yaml"
в целом, я знаю про этот подход и согласен, что он более правильный и надежный, 
но конкретно в случае тестового окружения мне кажется это избыточно. wait-for-it к которому прибавляется 1 секунда ожидания прекрасно справляется с задачей в 100% случаев.
а остальные сервисы ждут еще кролика, который поднимается ощутимо дольше бд.

а в продакшене вообще ситуации с поднимающейся бд не может быть, так что  думаю для интеграционного тестирования можно сделать допущение, чтобы было проще и понятнее.

2020-09-28 10:44 UTC, kulti commented on hw12_13_14_15_calendar/deployments/docker-compose.yaml
> +    command: sh -c "/wait && /app/calendar migrate up --config config.yaml"
Насчет 100% спорное утверждение. Никто не гарантирует, что ы ту секунду, что скрипт ожидание спит, будет именно БД подниматься, а не, скажем, выгружаться бэкапы на s3.

Хорошо, что знаете. Исправлять тут ничего не нужно — это просто совет на будущее и для реальных боевых задач.

2020-09-28 10:49 UTC, kulti approved these changes
Я правильно понял, что вы решили не делать отправку уведомлений? Без них принято на 8/10.

Все остальное хорошо. Думаю, финальный проект у вас должен тоже отлично получиться.

2020-09-28 11:32 UTC, merged