hw04 solution
FreakyGranny/otus pull request #4
Opened 2020-06-21 13:56 UTC by FreakyGranny

## Домашнее задание №4 «LRU-кэш»

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2020-06-25 07:12 UTC, kulti approved these changes
Петр, добрый день.

Классное ДЗ. 10/10.

Есть несколько моментов, которые можно улучшить. На количество баллов это не влияет.

2020-06-25 07:12 UTC, kulti commented on hw04_lru_cache/list_test.go
> +	t.Run("one-side-push", func(t *testing.T) {
Название сабтеста такое же, как и на 68 строке.

2020-06-25 07:12 UTC, kulti commented on hw04_lru_cache/list_test.go
> +		l.pop(p)
Лучше тестировать сценарии использования, а не внутренности.

2020-06-25 07:12 UTC, kulti commented on hw04_lru_cache/list.go
> +func (l *list) InsertBefore(root *listItem, new *listItem) {
Почему этот внутренний метод публичный?

2020-06-25 07:12 UTC, kulti commented on hw04_lru_cache/list.go
> +	storage   map[string]*listItem
Сложность добавления/поиска в map - амортизированное О(1). Т.е. это часто О(1), но не всегда. В задании сказано, что сложность всех операций должна быть О(1).

Если я правильно понял, storage используется только для проверки, есть ли item в списке, чтобы в Remove не удалять то, чего нет. Почему нет похожей проверки для MoveFront? Там тоже можно подсунуть элемент из другого списка.

Предлагаю:
1. Удалить storage и проверку, т.к. в задании сказано, что "Гарантируется, что методы Remove и MoveToFront вызываются от существующих в списке элементов".
2. Если хочется оставить подобную проверку, то подумать, как обойтись без map. Могу дать подсказку, в каком направлении подумать.

2020-06-25 07:12 UTC, kulti commented on hw04_lru_cache/cache.go
> +	return v.val, ok
Выглядит так, что можно заменить от `v.val` на `v.qpointer.Value`. Тогда поле val можно будет удалить - метод Set тоже упроститься.

2020-06-25 07:25 UTC, kulti commented on hw04_lru_cache/list.go
> +	storage   map[string]*listItem
Ох... тут еще и рефлексия в listItem.String.

Поспешил я принять ДЗ :) Надеюсь, вы это поправите.

2020-06-25 07:37 UTC, kulti requested changes
Давайте все-таки немного поправим решение?

2020-06-25 07:37 UTC, kulti commented on hw04_lru_cache/cache.go
> +	return v.val, ok
Понял, в чем дело. Ключи в списке хранятся ключи, а не значения. Так что тут все в порядке. Проблема в другом месте.

2020-06-25 07:37 UTC, kulti commented on hw04_lru_cache/cache.go
> +		delete(c.cacheMap, elem.String())
String может делать все, что угодно. Уже писал выше, что плохо, что там Printf (рефлексия).

Правильный подход в данном случае такой:
1. lruCache знает, что хранит в списке строки.
2. Можно безопасно кастить interface к нужному типу.

2020-06-25 15:13 UTC, FreakyGranny commented on hw04_lru_cache/list_test.go
> +	t.Run("one-side-push", func(t *testing.T) {
спасибо, поправил

2020-06-25 15:13 UTC, FreakyGranny commented on hw04_lru_cache/list.go
> +func (l *list) InsertBefore(root *listItem, new *listItem) {
исправил

2020-06-25 15:14 UTC, FreakyGranny commented on hw04_lru_cache/cache.go
> +		delete(c.cacheMap, elem.String())
переписал метод, на использование свича по типу

2020-06-25 15:15 UTC, FreakyGranny commented on hw04_lru_cache/list_test.go
> +		l.pop(p)
хотел добиться 100% покрытия, понял ошибку, удалил тест

2020-06-25 15:18 UTC, FreakyGranny commented on hw04_lru_cache/list.go
> +	storage   map[string]*listItem
storage удалил, 
если не сложно подскажите как можно реализовать проверку нахождения в списке без мапа и без полного обхода. 

Была мысль добавлять в каждый элемент указатель на лист - если указатель удаляемого элемента равен указателю списка - значит все ок.

2020-06-25 17:42 UTC, kulti commented on hw04_lru_cache/cache.go
> +		delete(c.cacheMap, elem.String())
listItem не знает, что в нем лежит. Непонятно, зачем ему вообще метод String. Тем более такой.

Я говорил о том, что lruCache знает, что лежит в listItem, т.к. сам туда и кладет. Можно в этой строчке сделать так: `elem.Value.(string)`.

2020-06-25 17:42 UTC, kulti commented on hw04_lru_cache/list.go
> +	storage   map[string]*listItem
Правильная мысль. Обычно так и делают. Пример: https://golang.org/src/container/list/list.go#L24.

2020-06-25 17:42 UTC, kulti submitted a review, later dismissed

2020-06-26 01:21 UTC, FreakyGranny commented on hw04_lru_cache/list.go
> +	storage   map[string]*listItem
понял, спасибо

2020-06-26 01:21 UTC, FreakyGranny commented on hw04_lru_cache/cache.go
> +		delete(c.cacheMap, elem.String())
понял, так действительно проще получается

2020-06-26 06:41 UTC, kulti approved these changes

2020-06-27 00:35 UTC, merged